name: "create a pull request from development to main"

on:
  push:
    branches:
      - "development"

#this action creates a pull request from the development to the main branch
#but before that runs tests to check if there are no conflicts in the push files

jobs:
  mainPromotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Reset promotion branch
        run: |
          git fetch origin development:development
          git reset --hard development
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: main-release #creates a temporary branch for the pull request